namespace Rotations.PVE.Ranged_Magic;

[Flags]
public enum BlmState
{
    Default,
    NoMana,
    AtLeastEightHundredMana,
    FullMana,
    Moving,
    AstralFire1,
    AstralFire2,
    AstralFire3,
    AstralFireLessThan3Sec,
    UmbralIce1,
    UmbralIce2,
    UmbralIce3,
    UmbralIceLessThan3Sec,
    Xenoglossy1,
    Xenoglossy2,
    Xenoglossy3,
    XenoglossyReadyLessThan3Sec,
    FlareStar,
    Polyglot,
    DoTLessThan3Sec,
    Firestarter,
    Thunderhead,
    Amplifier,
    Swiftcast,
    TripleCast1,
    TripleCast2,
    TripleCast3,
    Manafont,
    LucidDreaming,
    Transpose,
    UmbralHeart1,
    UmbralHeart2,
    UmbralHeart3
}